---
references:
- id: abescatTerrainsSansContact2022
  abstract: "Cet article propose un retour d’expérience sur les stratégies d’adaptation et les apprentissages qui ont permis à dix doctorant.es du Centre de recherches internationales (CERI, CNRS/Sciences Po) de poursuivre leurs recherches après l’instauration des mesures liées à la crise sanitaire du Covid-19. Malgré des méthodes et des terrains variés, nos recherches, tant sur la forme que sur le fond, ont été radicalement affectées par la pandémie. Nous montrons comment la conduite d’une recherche doctorale «\_sans contact\_» nous a poussés à développer des méthodes alternatives de récolte des données, à reformuler nos questions de recherche et à modifier nos objets d’analyse. Selon nous, la recherche qualitative à distance conduit à opérer un recentrement épistémologique, tant géographique qu’institutionnel. Elle détourne également le regard des chercheurs et chercheuses des acteurs et actrices non connecté.es ainsi que des pratiques informelles. Nous interrogeons enfin la dimension heuristique de ces «\_bricolages\_» méthodologiques, en réalité contingents à toute recherche en sciences sociales, et la valeur épistémologique de ces méthodes alternatives en proposant une formalisation de celles-ci."
  accessed:
    - year: 2022
      month: 11
      day: 18
  author:
    - family: Abescat
      given: Camille
    - family: Barnier-Khawam
      given: Pablo
    - family: Chaplain
      given: Alix
    - family: Colomba-Petteng
      given: Léonard
    - family: Duboscq
      given: Claire
    - family: Jacquin
      given: Ronan
    - family: Miljkovic
      given: Elisabeth
    - family: Russo
      given: Sophie
    - family: Sihra
      given: Jusmeet S.
    - family: Vergonjeanne
      given: Anaëlle
  citation-key: abescatTerrainsSansContact2022
  container-title: Tracés. Revue de Sciences humaines
  container-title-short: Tracés
  DOI: 10.4000/traces.13768
  ISSN: 1763-0061
  issue: '42'
  issued:
    - year: 2022
  language: fr
  license: https://creativecommons.org/licenses/by-nc-nd/4.0/
  page: 75-93
  source: journals.openedition.org
  title: >-
    Terrains “sans contact” : l’enquête qualitative en sciences sociales pendant
    la pandémie
  title-short: Terrains « sans contact »
  type: article-journal
  URL: https://journals.openedition.org/traces/13768

- id: balzacqIdeasIdeologyGrand2021
  abstract: >-
    A field once dominated by rationalist assumptions, grand strategy is
    beginning to make room for alternatives approaches. Recently, scholars have
    drawn on discourse theory to explore how narratives influence the
    directionality of grand strategy. Others have emphasized the importance of
    ideology as a driver of grand strategy, but have failed to specify how
    ideology interacts with different levels of grand strategizing – creation,
    mobilization, and implementation. In this essay, we make two interrelated
    arguments: first is that that ideology is constitutive of the meaning
    structure that underlies grand strategy.  Second is that ideology’s primary
    function is to invest grand strategy with clarity (if not simplicity),
    stability and coherence. We identify three distinct ways in which ideology
    can shape a nation’s grand strategy, including threat identification,
    mobilization and extraction of resources, and ideological balancing. We use
    a range of exploratory cases to assess ideology’s status in grand
    strategizing.
  author:
    - family: Balzacq
      given: Thierry
    - family: Barnier-Khawam
      given: Pablo
  citation-key: balzacqIdeasIdeologyGrand2021
  collection-title: Oxford handbooks series
  container-title: The Oxford Handbook of Grand Strategy
  DOI: 10.1093/oxfordhb/9780198840299.013.46
  editor:
    - family: Balzacq
      given: Thierry
    - family: Krebs
      given: Ronald R.
  event-place: Oxford
  ISBN: 978-0-19-884029-9
  issued:
    - year: 2021
  language: en
  license: All rights reserved
  page: 159-172
  publisher: Oxford University Press
  publisher-place: Oxford
  source: Library of Congress ISBN
  title: Ideas and Ideology in Grand Strategy
  type: chapter

- id: balzacqIdeologyInternationalSecurity2020
  abstract: >-
    This essay examines both the epistemological underpinnings and implications
    of ideology in international security. It does so with an eye toward
    assessing the benefits of a constitutive approach, as compared to a causal
    perspective that understands ideology as falling within a causal-effect
    cognitive process. We then put our theoretical argument to work by studying
    neoconservatism’s influence on US foreign policy under George W. Bush. This
    case allows us to disclose competition between ideologies, understand the
    role of ideology in the process of decision-making and vet the extent to
    which ideology acts on policy choices. The essay advocates a social theory
    of ideology that can tap into the moral stances that shape discussions about
    ideology in international security.
  accessed:
    - year: 2020
      month: 9
      day: 14
  author:
    - family: Balzacq
      given: Thierry
    - family: Barnier-Khawam
      given: Pablo
  citation-key: balzacqIdeologyInternationalSecurity2020
  collection-title: Staat – Souveränität – Nation
  container-title: Ideologies in World Politics
  DOI: 10.1007/978-3-658-30512-3_4
  editor:
    - family: Giesen
      given: Klaus-Gerd
  event-place: Wiesbaden
  ISBN: 978-3-658-30512-3
  issued:
    - year: 2020
  language: en
  license: All rights reserved
  page: 51-70
  publisher: Springer Fachmedien
  publisher-place: Wiesbaden
  source: Springer Link
  title: Ideology and International Security
  type: chapter
  URL: https://doi.org/10.1007/978-3-658-30512-3_4

- id: barnier-khawamAutodeterminationCommePrincipe2023
  abstract: >-
    L'appropriation de la revendication d'autodétermination par les peuples
    autochtones de la Bolivie et du Chili est caractérisée par une profonde
    ambivalence. Elle procède, d'abord, de l'histoire de la politique
    internationale des années 1970 de ces deux pays pour, ensuite, aboutir à une
    redéfinition de l'autodétermination du fait de deux facteurs. Le premier est
    la transformation induite par la trajectoire historique étudiée, de 1970 à
    2019, et le deuxième renvoie à la nature des nouveaux acteurs que sont les
    peuples autochtones, en comparaison avec les acteurs étatiques qui étaient,
    auparavant, les porteurs de cette revendication. La revendication
    d'autodétermination par les peuples autochtones de la Bolivie et du Chili
    fait donc l'objet d'une évolution historique déterminée par des contextes
    nationaux distincts et une commune mobilisation internationale et
    transnationale. Selon les décennies, elle s'agence comme une demande qui
    s'hybride ou conteste les politiques mises en œuvre par les deux États en
    question vis-à-vis des peuples autochtones. Elle reste, cependant, toujours
    en lien avec la volonté d'établir une autonomie politique en refusant la
    sécession. Cette transformation de l'autodétermination contredit alors les
    développements internationaux relatifs à ce principe étroitement associé à
    la souveraineté étatique. Ainsi, les peuples autochtones sont acteurs d'un
    changement structurel majeur en ce qui concerne la définition de
    l'autodétermination et de ses effets au niveau international. Afin de saisir
    cette évolution socio-historique, la thèse met en œuvre une étude
    comparative de cas les plus différents entre la Bolivie et le Chili et une
    ethnographie de la participation contemporaine des peuples autochtones dans
    les instances onusiennes.
  accessed:
    - year: 2023
      month: 6
      day: 9
  author:
    - family: Barnier-Khawam
      given: Pablo
  citation-key: barnier-khawamAutodeterminationCommePrincipe2023
  genre: Science politique
  issued:
    - year: 2023
  language: fr
  license: All rights reserved
  number-of-pages: '680'
  publisher: Institut d'études politiques de Paris - Sciences Po
  source: theses.hal.science
  title: >-
    L’autodétermination comme principe d’autonomie politique : Histoire et
    appropriation d’un droit équivoque en Bolivie et au Chili de 1970 à 2019
  title-short: L’autodétermination comme principe d’autonomie politique
  type: thesis
  URL: https://theses.hal.science/tel-04124332

- id: barnier-khawamEntrePlurinationaliteAutonomie2023
  abstract: "Introduction La place des peuples autochtones dans les sociétés latino-américaines a, au moins depuis les indépendances du début du XIXe siècle, oscillé entre assimilation et relégation. À partir du XXe siècle, l’indigénisme introduit des politiques gouvernementales qui, pour la première fois, considèrent la place de l’«\_Indien\_» dans la politique latino-américaine. La loi n°\_17.729, adoptée en septembre 1972 par le gouvernement de Salvador Allende, en est un bon exemple par sa focalisation s..."
  accessed:
    - year: 2023
      month: 3
      day: 8
  author:
    - family: Barnier-Khawam
      given: Pablo
  citation-key: barnier-khawamEntrePlurinationaliteAutonomie2023
  container-title: IdeAs. Idées d'Amériques
  DOI: 10.4000/ideas.14733
  ISSN: 1950-5701
  issue: '21'
  issued:
    - year: 2023
  language: fr
  license: https://creativecommons.org/licenses/by-nc-nd/4.0/
  source: journals.openedition.org
  title: >-
    Entre plurinationalité et autonomie. Les peuples autochtones dans le système
    politique chilien (2019-2022)
  type: article-journal
  URL: https://journals.openedition.org/ideas/14733

- id: barnier-khawamInternacionalizacionMapucheEntre2019
  abstract: >-
    El presente trabajo surge de la contradicción entre el creciente llamado a
    ser miembro del mundo global, y el desarrollo de identidades particulares
    que se constituyen a partir de las posibilidades que emanan de esa
    integración en el espacio global. Lo anterior muestra que la
    internacionalización, que se divide en una dinámica nacional de proyección
    internacional y una dinámica internacional de penetración nacional, es clave
    en la construcción identitaria de los mapuche. La metodología del trabajo se
    funda en una perspectiva comprensiva del fenómeno en base a la realización
    de entrevistas a diversos actores, la consulta de archivos, y una
    observación participante en el interior del Ministerio de Relaciones
    Exteriores de Chile. Los resultados de esta investigación muestran que la
    internacionalización de los mapuche conduce a la división de su identidad
    entre dos referentes de identificación que son el de “indígena” y el de
    “nación”, cada uno con discursos y prácticas específicas.
  accessed:
    - year: 2019
      month: 8
      day: 3
  author:
    - family: Barnier-Khawam
      given: Pablo
  citation-key: barnier-khawamInternacionalizacionMapucheEntre2019
  container-title: Polis. Revista Latinoamericana
  DOI: 10.32735/s0718-6568/2019-n52-1364
  ISSN: 0718-6568
  issue: '52'
  issued:
    - year: 2019
  language: es
  license: Copyright (c) 2019 Polis Revista Latinoamericana
  page: 106-120
  source: polis.ulagos.cl
  title: 'La internacionalización de los Mapuche: entre pueblo indígena y nación'
  title-short: La internacionalización de los Mapuche
  type: article-journal
  URL: http://polis.ulagos.cl/index.php/polis/article/view/1364

- id: barnier-khawamLuisMartinezAndrade2023
  abstract: >-
    Auteur de travaux en lien avec le marxisme, la           théologie de la
    libération, l’écologie et la pensée décoloniale,           Luis Martínez
    Andrade propose dans ce livre une analyse de portraits          
    intellectuels. Si la comparaison reste implicite, des résonances          
    entre les trajectoires d’une diversité de penseurs critiques, que          
    sont principalement Karl Marx, José Carlos Mariátegui, Walter          
    Benjamin, Max Horkheimer, Michael Löwy, Franz Hinkelammert, Enr...
  accessed:
    - year: 2023
      month: 6
      day: 19
  author:
    - family: Barnier-Khawam
      given: Pablo
  citation-key: barnier-khawamLuisMartinezAndrade2023
  container-title: Nuevo Mundo Mundos Nuevos
  DOI: 10.4000/nuevomundo.93069
  ISSN: 1626-0252
  issued:
    - year: 2023
  language: fr
  license: https://creativecommons.org/licenses/by-nc-nd/4.0/
  publisher: EHESS
  source: journals.openedition.org
  title: >-
    Luis Martínez Andrade, Dialectique de la modernité et socialisme
    indo-américain. Essais d’histoire intellectuelle
  type: article-journal
  URL: https://journals.openedition.org/nuevomundo/93069

- id: barnier-khawamMapucheRevendicationNation2019
  abstract: >-
    Les Mapuche sont souvent présentés comme l'un des peuples autochtones
    d'Amérique latine ayant montré la capacité de résistance la plus farouche
    face au colonisateur espagnol et, ensuite, face au processus de construction
    des Etats-nations chilien et argentin. Ce caractère attribué nécessite
    d'être réinscrit dans le temps long de l'histoire en prenant en compte
    l'importance des processus sociaux relatifs à la construction identitaire.
    Au travers de l'usage de catégories telles que "peuples autochtone" ou
    "nation", dans un contexte d'internationalisation aujourd'hui croissante des
    acteurs, cette construction identitaire mapuche interpelle l'Etat
    "monoculturel"
  author:
    - family: Barnier-Khawam
      given: Pablo
  citation-key: barnier-khawamMapucheRevendicationNation2019
  collection-title: Inter-National
  contributor:
    - family: Bellier
      given: Irène
  event-place: Paris
  ISBN: 978-2-343-17571-3
  issued:
    - year: 2019
  language: fr
  license: All rights reserved
  number-of-pages: '186'
  publisher: L'Harmattan
  publisher-place: Paris
  title: Les Mapuche et la revendication d'une nation
  type: book
  URL: >-
    https://www.editions-harmattan.fr/livre-les_mapuche_et_la_revendication_d_une_nation_preface_d_irene_bellier_pablo_barnier_khawam-9782343175713-63303.html

- id: barnier-khawamMouvementPolitiqueMapuche2021
  abstract: >-
    Les « années 68 » constituent un contexte de transformation mondiale. De
    Paris à Santiago, l’autorité tutélaire est remise en cause. L’élection au
    Chili du chrétien-démocrate Eduardo Frei, en 1964, avec son slogan « patria
    joven », est caractéristique de ce contexte qui se veut à l’origine de
    réformes sociales d’ampleur. La jonction entre un milieu juvénile et paysan
    au moment de la réforme agraire amorce un processus de distanciation
    vis-à-vis de structures sociales ayant une forte capacité de contrôle, comme
    les partis politiques et les institutions étatiques. La mobilisation des
    Mapuche à cette époque s’inscrit dans cette distanciation qui a pour
    corollaire une autonomisation de leur mouvement politique. L’objectif de cet
    article est d’exposer, par l’intermédiaire de plusieurs entretiens et des
    recherches d’archives, les processus à l’œuvre dans la construction de
    l’autonomie des Mapuche, à la fois comme mouvement et comme revendication,
    en faisant remonter l’origine de cette dernière aux « années 68 ».
  accessed:
    - year: 2022
      month: 3
      day: 17
  author:
    - family: Barnier-Khawam
      given: Pablo
  citation-key: barnier-khawamMouvementPolitiqueMapuche2021
  container-title: Cahiers des Amériques latines
  container-title-short: CAL
  DOI: 10.4000/cal.13650
  ISSN: 1141-7161, 2268-4247
  issue: '97'
  issued:
    - year: 2021
  language: fr
  license: All rights reserved
  page: 213-231
  source: DOI.org (Crossref)
  title: >-
    Le mouvement politique mapuche : dépendance et autonomisation dans les
    années 1968
  title-short: Le mouvement politique mapuche
  type: article-journal
  URL: http://journals.openedition.org/cal/13650

- id: barnier-khawamSubsidiariedadEducacionChile2021
  abstract: >-
    A partir de un estudio histórico e ideológico del concepto de
    subsidiariedad, este artículo propone un análisis de su aplicación en el
    ámbito de la educación en Chile. De esta manera, se demuestra el rol del
    jurista Jaime Guzmán en la conjugación de la tradición católica con el
    pensamiento neoliberal, al integrar la subsidiariedad en el sistema jurídico
    chileno. La ambivalencia de este principio de organización institucional
    permite justificar el carácter democrático del sistema educativo gracias a
    la libertad de enseñanza que consagra. La transición democrática profundiza
    este modelo con una ampliación de la oferta privada en la educación
    superior, lo que demuestra una continuación ideológica en cuanto al concepto
    de subsidiariedad. Sin embargo, este mismo concepto puede tener otro
    contenido ideológico partiendo de la idea que la educación debe entenderse
    como un ámbito social fuera de la lógica de mercado, como lo demuestran los
    movimientos estudiantiles en Chile. Una propuesta horizontal de la
    subsidiariedad puede así ser teorizada.
  accessed:
    - year: 2021
      month: 2
      day: 1
  author:
    - family: Barnier-Khawam
      given: Pablo
  citation-key: barnier-khawamSubsidiariedadEducacionChile2021
  container-title: Revista Iberoamericana de Educación Superior
  DOI: 10.22201/iisue.20072872e.2021.33.865
  ISSN: 2007-2872
  issue: '33'
  issued:
    - year: 2021
  language: es
  license: Derechos de autor 2021
  page: 197-212
  source: www.ries.universia.unam.mx
  title: >-
    Subsidiariedad y educación en Chile: estudio histórico de un principio
    político polisémico
  title-short: Subsidiariedad y educación en Chile
  type: article-journal
  URL: https://www.ries.universia.unam.mx/index.php/ries/article/view/865
  volume: '12'

- id: eichlerCriminalizationSecuritizationOther2022
  abstract: >-
    This article critically examines the contemporary ‘securitization paradigm’
    adopted throughout the Chilean jurisdiction. Emphasis is placed on its
    explicit misuse and its arbitrary effects on the Mapuche people in light of
    Chile’s anti-terrorism legislation. The law thereby assumes a twofold
    function. ‘Judicialization strategies’ are employed by different organs of
    the State, resulting in the criminalization and ultimately the silencing of
    indigenous protest and forms of representation in the public space. These
    potentially transform relations between the State and its subjects,
    demanding a repositioning of indigenous agendas and representation under the
    constitutional umbrella. Conversely, judicialization also assumes a
    mediating role through the virtuous effects of international law and
    Inter-American human rights jurisprudence. The newly commencing
    constitutional era may further spur such developments, potentially exerting
    essential decolonizing effects on State institutions and society at large.
  accessed:
    - year: 2022
      month: 2
      day: 18
  author:
    - family: Eichler
      given: Jessika
    - family: Barnier-Khawam
      given: Pablo
  citation-key: eichlerCriminalizationSecuritizationOther2022
  container-title: Journal of Human Rights Practice
  container-title-short: Journal of Human Rights Practice
  DOI: 10.1093/jhuman/huab041
  ISSN: 1757-9627
  issue: '2'
  issued:
    - year: 2022
  language: en
  license: All rights reserved
  page: 357-385
  source: Silverchair
  title: >-
    Criminalization, Securitization and other Forms of Illegalizing Indigenous
    Contestations in Chile: Responses from Constitutional Law and Inter-American
    Jurisprudence on Mapuche People’s Rights
  title-short: >-
    Criminalization, Securitization and other Forms of Illegalizing Indigenous
    Contestations in Chile
  type: article-journal
  URL: https://doi.org/10.1093/jhuman/huab041
  volume: '13'
...
